### ISSUE TITLE
train_and_eval correct behavior

### ISSUE THREAD

**Issue by jjtan** [conversationai/conversationai-models#165]
Was using tensorboard and getting fairly erratic eval points when training my model (e.g. one at 500 steps, next one at 7k steps). Am I misinterpreting our train_with_eval function?

If not, given that tf's train_with_eval preserves where it left off (as of https://github.com/tensorflow/tensorflow/issues/19062#issuecomment-412738707), can we stick it in a loop so we can get more eval points? I wrote some code that seems to work in this branch: https://github.com/conversationai/conversationai-models/tree/train-eval-loop

But may be missing something with how checkpoints interact with when evaluation happens.

**Comment by fprost** [comment]
I think you want to lower your throttle_secs variable.
The way the checkpoint works:
- Every x steps (defined by runConfig), they evaluate if you run eval. 
- One of the rule to run eval is the throttle_secs. Currently it will not run it if last eval was less than 10minutes ago.
You can put 1 if you want to remove the throttle_secs constraint.

 https://www.tensorflow.org/api_docs/python/tf/estimator/EvalSpec

**Comment by nthain** [comment]
Did this resolve the issue @jjtan?
