### ISSUE TITLE
Error running tf_gru_attention on many_communities data

### ISSUE THREAD

**Issue by nthain** [conversationai/conversationai-models#206]
When running the tf_gru_attention model on the many communities data, the graph runs for a few hundred steps before failing with the following error 

tensorflow.python.framework.errors_impl.InvalidArgumentError: 0-th value returned by pyfunc_0 is double, but expects int64
	 [[Node: PyFunc = PyFunc[Tin=[DT_STRING], Tout=[DT_INT64], token="pyfunc_0", _device="/device:CPU:0"](ParseSingleExample/ParseSingleExample)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?], [?], [?,?], [?]], output_types=[DT_FLOAT, DT_INT32, DT_INT64, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

The script used to run this model was:

GCS_RESOURCES="gs://kaggle-model-experiments/resources"

python -m tf_trainer.tf_gru_attention.run \
  --train_path="${GCS_RESOURCES}/transfer_learning_data/many_communities/20181105_train.tfrecord" \
  --validate_path="${GCS_RESOURCES}/transfer_learning_data/many_communities/20181105_validate.tfrecord" \
  --embeddings_path="${GCS_RESOURCES}/glove.6B/glove.6B.100d.txt" \
  --model_dir="tf_gru_attention_local_model_dir" \
  --labels="removed" \
  --label_dtypes="int"

**Comment by sorensenjs** [comment]
There are records that are missing the 'removed' feature, here's the first one

1194566 : {     # (tensorflow.Example) size=257B
  features: {   # (tensorflow.Features) size=254B
    feature: {  # (tensorflow.Features.FeatureEntry) size=200B
      key  : "comment_text"     # size=12
      value: {  # (tensorflow.Feature) size=183B
        bytes_list: {   # (tensorflow.BytesList) size=180B
          value: [ "As I was saying below ya, he was, but I gave him another look at who he was and found he wasn’t that bad.\n\nNot going against you, totally understand where you are coming from." ]        # size=177; fp64=b21cc8e41af3b229; fp2011=3c8e71d8d6130d06
        }       # features.feature[0].value.bytes_list
      } # features.feature[0].value
    }   # features.feature[0]
    feature: {  # (tensorflow.Features.FeatureEntry) size=25B
      key  : "comment_id"       # size=10
      value: {  # (tensorflow.Feature) size=11B
        bytes_list: {   # (tensorflow.BytesList) size=9B
          value: [ "e8vegxh" ]  # size=7
        }       # features.feature[1].value.bytes_list
      } # features.feature[1].value
    }   # features.feature[1]
    feature: {  # (tensorflow.Features.FeatureEntry) size=22B
      key  : "subreddit"        # size=9
      value: {  # (tensorflow.Feature) size=9B
        bytes_list: {   # (tensorflow.BytesList) size=7B
          value: [ "4chan" ]    # size=5
        }       # features.feature[2].value.bytes_list
      } # features.feature[2].value
    }   # features.feature[2]
  }     # features
}

I thought we were robust to missing features?

**Comment by sorensenjs** [comment]
Ugh, batch size affects. I'm trying to find a minimal repro.
