### ISSUE TITLE
Add documentation for downloading Glove embeddings

### ISSUE THREAD

**Issue by ericagreene** [conversationai/conversationai-models#48]
Currently, the Keras model training pipeline assumes you have a glove embeddings file in `/local_data/glove.6B/glove.6B.100d.txt`. It doesn't look like we have any documentation about were to get those embeddings and where to put them. 

We should:
* add documentation to the README 
* add logic to our run_local shell scripts that that automatically downloads them from Cloud Storage if they don't exist and puts them in the right place [optional, but would be super great]

**Comment by nthain** [comment]
This is fixed in the experiments directory as we read the embeddings from GCS.
