### ISSUE TITLE
Add Kaggle Competition Winner's Models

### ISSUE THREAD

**Issue by nthain** [conversationai/conversationai-models#59]
Since we have access to the code from the Winner's of the Kaggle competition, let's try to add their models to this framework. This will also test our ability to build a framework that is robust to quickly incorporating models from external sources.

**Comment by ericagreene** [comment]
Great idea. 

What do you mean by the winner's model though? It sounds like they used an ensemble of a few dozen models. Maybe we could add their 3 top performing models?

**Comment by nthain** [comment]
I think between them, there were maybe 10 model architectures (albeit with different embeddings and hyperparameters). Adding the top 3 would be a good start. They've already written the model functions for us (though we should check what license they were released under) so we should see if we can adapt the framework to just load those with minimal pain. 

The general goal would be to figure out what changes need to be made to quickly import other good performing models developed externally.
